# Generated by Django 5.1.7 on 2025-04-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
